name: My Actions

on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        name: Set up Python
      - uses: actions/checkout@v4
        name: Check out code
      - run: pip install -r requirements.txt
        name: Install dependencies
      - name: Run tests
