name: My Actions

on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Clone the project
          uses: actions/checkout@v4
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Run tests
